li t0, 0x809903f7
li t1, 0x80abf992
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5cb21ce8
li t1, 0xdc8e1ce8
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7b4c81fb
li t1, 0xff55fcc9
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd060e9
li t1, 0x47676b
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x13bf430a
li t1, 0x330107f6
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa64a71a6
li t1, 0xe6ad3fe3
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb546a272
li t1, 0xab2b7a69
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x53839951
li t1, 0x579c9951
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x673a52ce
li t1, 0xc13e44a6
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x366156da
li t1, 0x374256da
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3f1d2967
li t1, 0x409f2253
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe2aba66b
li t1, 0xe2aba66b
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe0179744
li t1, 0x2e468bb
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdd7a8c86
li t1, 0xdd167387
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x108bcba2
li t1, 0x1172345d
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x60677300
li t1, 0x62677300
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa5dce626
li t1, 0x8f12e3bc
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7cfc2273
li t1, 0x6cc950b7
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x12ee7313
li t1, 0x4f8971de
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe1fe3139
li t1, 0xa1e5a85a
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe0229f33
li t1, 0x449a5e5
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x599e4c9c
li t1, 0x599ee7c0
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe8884c6e
li t1, 0x360f2b60
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xba6c48d6
li t1, 0xb81748d6
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x74442637
li t1, 0x1a0795b0
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x90b6338e
li t1, 0xb00a9fdb
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8b5d8876
li t1, 0xdd419a5
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x937c7845
li t1, 0x9b057845
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfd37c7cc
li t1, 0x9041f540
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa983f7d7
li t1, 0x29832c18
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8202e011
li t1, 0xde8b0332
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd7ec9a39
li t1, 0xd398dada
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x41017008
li t1, 0xe7458199
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbf8c4d5c
li t1, 0xbf8c6d2d
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8914f7
li t1, 0x185fa18b
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc45da503
li t1, 0xe4420a00
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa2f7c731
li t1, 0x93e9ed39
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x22eabaa2
li t1, 0x2aeabaa2
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd424f23b
li t1, 0xf05182dc
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5a7b73cc
li t1, 0x5b880ed9
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea12791d
li t1, 0xf828c16e
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc251b9e6
li t1, 0xc651036c
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf2640fde
li t1, 0x4aafe649
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc857d2fb
li t1, 0xd857d2fb
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x96fc491d
li t1, 0xe6e9f93a
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea174451
li t1, 0xca8f5c57
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4a7e248e
li t1, 0xe374fc9d
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcf8ba228
li t1, 0xcec7ae2b
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf3435b5a
li t1, 0xb7538774
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8f529545
li t1, 0xcf6c8b42
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcf5de4b0
li t1, 0x9d403a80
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbbbe0ef3
li t1, 0xabb919f6
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7352bb45
li t1, 0x8849e47a
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1d484328
li t1, 0x1fd3d0ac
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x30a95da2
li t1, 0xcc24f23d
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5b242194
li t1, 0x5369e856
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8aa8e7cc
li t1, 0x24fb8024
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3e85549b
li t1, 0xbebba87c
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x455473e6
li t1, 0x527dc012
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xaac2aa4d
li t1, 0x2addd43e
rem t2, t0, t1
rem t3, t1, t0
rem t4, t0, t0
rem t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

