li t0, 0xcf114d89
li t1, 0xcf3d8437
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x305eba4e
li t1, 0x38856b49
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x787ca32e
li t1, 0x12cd6b08
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xed9b4a95
li t1, 0xec369477
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x249fda45
li t1, 0x69174792
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xdf6c0531
li t1, 0xa7a9286d
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xa0ce0095
li t1, 0xa0e1726d
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xac75ef6a
li t1, 0x531e8d82
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x373e7cfa
li t1, 0xec2ed4e7
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xd4c21385
li t1, 0xd0d1651c
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xf3e30350
li t1, 0x283d6411
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x1e3cdcfc
li t1, 0x160916ca
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xcc079744
li t1, 0x32a028ba
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x3bacc8e
li t1, 0x34e718f
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x338bcba2
li t1, 0x1b72345d
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x3639b6d4
li t1, 0x360fb6d4
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xa5dce626
li t1, 0x9612e3b8
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x8ffcbff0
li t1, 0x8fc1bff0
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x53ae7313
li t1, 0x4fc971de
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x17be56d7
li t1, 0x16be56d7
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x7d7739c9
li t1, 0x43c4b8ef
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x427f189c
li t1, 0xbd72542d
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x4e229f73
li t1, 0x3749a5e5
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xb79d4d9c
li t1, 0x4137e6c0
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xea884c6e
li t1, 0x340f2b60
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x708a671c
li t1, 0x728a3db6
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x75442677
li t1, 0x1a0795b0
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xcf633cf
li t1, 0xc0a9fda
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x86bb10ec
li t1, 0x9ba8334a
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x1afb84fc
li t1, 0x9a8984fc
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x835d8976
li t1, 0xcd418a5
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x587d8f69
li t1, 0x59448f69
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x6d37c7cc
li t1, 0xc041f540
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x3b98d433
li t1, 0x7b2cd433
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x9202e011
li t1, 0xde8b0332
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xb3904c3
li t1, 0x1b3904c3
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xc1017008
li t1, 0xe7458199
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xcdcc4d5c
li t1, 0xc5cc6d2d
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xe280b804
li t1, 0x77a2c0cc
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x38bb268e
li t1, 0x3a2636b6
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xf9405c02
li t1, 0x3bd16066
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xb23c9347
li t1, 0xb23c1b1b
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x70a02e01
li t1, 0x1ce8b033
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x96ac9a3
li t1, 0x90d8ded
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x3cdd898c
li t1, 0x1a842957
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x42264490
li t1, 0x43264490
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xa2f7c731
li t1, 0xdbe9ed39
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xdf46d84c
li t1, 0x9f3bd84c
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xe4c89fbc
li t1, 0xb55fcc92
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x7d160e90
li t1, 0x947666b0
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0x861df295
li t1, 0xdea4d332
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xde7f60fc
li t1, 0xfefe531d
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xd30ef94a
li t1, 0xe7526999
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

li t0, 0xa33fb07e
li t1, 0xabff298e
xor t2, t0, t1
sw t2, 4(sp)
xor t2, t1, t0
sw t2, 4(sp)
xor t2, t0, t0
sw t2, 4(sp)
xor t2, t1, t1
sw t2, 4(sp)

