li t0, 0xb79903f7
li t1, 0xb2abf992
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xffa2c1d2
li t1, 0x7f8eccd6
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x994c81fb
li t1, 0x6355fcc9
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9c8a60e9
li t1, 0x9c8a666b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xafbf430a
li t1, 0x3b0107f6
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd44a70a6
li t1, 0xd42d7fe3
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x146a272
li t1, 0xff2b7a69
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd187f901
li t1, 0xc9987327
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x651d2967
li t1, 0x659f2253
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9db09ea9
li t1, 0xaf217aa2
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe5179744
li t1, 0x26e468bb
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x397a8e86
li t1, 0xfd1e7187
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe5dce626
li t1, 0x9f12e3bc
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb1fc6273
li t1, 0xddc950b7
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x52ee7313
li t1, 0x4f8971de
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x68fe3139
li t1, 0x5ee4a85b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7b773989
li t1, 0x81c4b8ef
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x97f189c
li t1, 0xd72542d
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb8229f33
li t1, 0x4549a5e5
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe1dd19a7
li t1, 0xf13719a7
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf4884c6e
li t1, 0x3c0f2b60
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc975671d
li t1, 0xc9753fb6
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x40442637
li t1, 0x1b0795b0
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xecb2338e
li t1, 0xec0e8fdb
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6bb10ec
li t1, 0x1ba8334a
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd8f9d815
li t1, 0xdc8b833b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x815d8876
li t1, 0xcd419a5
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7aded0a
li t1, 0x7adc09d
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7f37c7cc
li t1, 0x9041f540
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe89cb7d7
li t1, 0xea2c2c18
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8202e011
li t1, 0xde8b0332
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x374d9839
li t1, 0x374ddada
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf080b804
li t1, 0xe7a2c0cc
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfbb268e
li t1, 0x182636b6
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x78202e01
li t1, 0x5de8b033
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2feec9a3
li t1, 0x1b898dad
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xaaf7c731
li t1, 0x93e9ed39
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7766c87b
li t1, 0x7f1b283d
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd17be398
li t1, 0xc9f4f69c
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5333643d
li t1, 0x570d941e
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd424f23b
li t1, 0xf45182dc
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xab3b73cc
li t1, 0xab8806d9
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea12791d
li t1, 0xf828c16e
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x201db9e6
li t1, 0x22c4036c
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe4c81fbc
li t1, 0xb45fcc92
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x26560e90
li t1, 0x2736e6b0
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf0640fde
li t1, 0x70afe649
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x728b0748
li t1, 0x7a3b3358
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa35ead78
li t1, 0x31939295
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x54898dcc
li t1, 0x55bcf4e5
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd1af56bc
li t1, 0x1949c94a
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd444c6e6
li t1, 0xe6de7a72
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6b890626
li t1, 0x3e377630
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8dabeebf
li t1, 0xadd3c9dc
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x69a2e6b
li t1, 0x2f88298d
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb9dc7a93
li t1, 0xbbd5100b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa013ba4d
li t1, 0xa4578653
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x567b085
li t1, 0x15d67ce0
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9009dd26
li t1, 0x922bc329
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8933d842
li t1, 0xc96b3e70
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcb5a43eb
li t1, 0x5b867301
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x109061ed
li t1, 0x18096bdd
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe4ad21f5
li t1, 0xafc33980
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd34830f6
li t1, 0xd284b5ee
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x59883d82
li t1, 0xe4720e55
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa72d95b7
li t1, 0xab7eae12
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa0c41ec1
li t1, 0x7239072a
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1996cadb
li t1, 0x13bf5709
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x54620f60
li t1, 0xb91c8395
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbecb656d
li t1, 0xa5dfab84
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x67e9781c
li t1, 0x59d7b3a
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb27f9271
li t1, 0xf2156476
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb3f4bc0e
li t1, 0x2cebd9d
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4cbfc938
li t1, 0x6c0ab23b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7aa4f37f
li t1, 0x33f4cc5b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9f566950
li t1, 0x1f39adf8
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf55279bf
li t1, 0x9bfa662d
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2b2b34a8
li t1, 0x291cd6fc
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x59f791a7
li t1, 0xfe6ea183
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd1c1798
li t1, 0xab29f9b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfa565ab
li t1, 0xcda4c254
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf1078600
li t1, 0xf2e5bb28
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6d2b2d5
li t1, 0xe6d2612a
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb903c300
li t1, 0xb872dd94
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8769596a
li t1, 0xf3693095
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3b81e180
li t1, 0x3cb96eca
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc1b4acb5
li t1, 0x79b4984a
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7fc0f0c0
li t1, 0x7c5cb765
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa0da565a
li t1, 0xfcda4c25
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4ee07860
li t1, 0x2e2e5bb2
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x53338655
li t1, 0x6cfeb487
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf7f9b1fc
li t1, 0xdaabd93c
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x82c76e52
li t1, 0x8cecc8d6
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8b755532
li t1, 0x83e9187b
p.slts t2, t0, t1
p.slts t3, t1, t0
p.slts t4, t0, t0
p.slts t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

