li t0, 0x89903f7
li t1, 0xf6abf992
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfb22c69e
li t1, 0xfb8ec69e
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe24c81fb
li t1, 0xe255fcc9
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8e730544
li t1, 0x8a730544
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x35bf430a
li t1, 0x350107f6
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x80c061c
li t1, 0x480c061c
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb546a272
li t1, 0xab2b7a69
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7186f901
li t1, 0x7599732f
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x673a52ce
li t1, 0xc13e44a6
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x31618eaa
li t1, 0x30428eaa
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbb1d2967
li t1, 0x6a9f2253
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc959ea9
li t1, 0xe957aa2
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6d179744
li t1, 0x2ee468bb
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7ad98e86
li t1, 0x72d9718f
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x328bcba2
li t1, 0x1772345d
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe53db9c9
li t1, 0xe18fb9c9
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf5dce626
li t1, 0xfd12e3bc
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa8eba6f
li t1, 0xa8eba6f
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x12ee7313
li t1, 0x4e8971de
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb17e3179
li t1, 0xb1e4a81b
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x28773989
li t1, 0xa6c4b8ef
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x347f189c
li t1, 0x3570542d
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe8229f33
li t1, 0x4549a5e5
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x319d4d9c
li t1, 0x7137e6c0
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe8884c6e
li t1, 0x240f2b60
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x526ccf4c
li t1, 0x4215cf4c
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4bb10ec
li t1, 0x1ba8334a
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9bc68f5a
li t1, 0x99c68f5a
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x835d8876
li t1, 0x2dd419a5
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xed7cec0a
li t1, 0xcd45c19d
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7d37c7cc
li t1, 0x9841f540
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc19c37a8
li t1, 0xc12e37a8
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x41017008
li t1, 0x6f458199
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcf764d14
li t1, 0x4f4c6d6d
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe080b804
li t1, 0x73a2c0cc
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x45bb268e
li t1, 0x452636b6
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf0405c02
li t1, 0x3bd16066
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3edd9347
li t1, 0xbe131a5b
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x208914f7
li t1, 0x385fa18b
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9955a503
li t1, 0xb90a0a20
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3cdd898c
li t1, 0xa842957
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x83881353
li t1, 0x932fc9d6
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa2f7c731
li t1, 0x9be9ed39
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2f3298c6
li t1, 0x273298c6
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea12791d
li t1, 0xf828c16e
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf43d236c
li t1, 0xf6c4236c
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf2640fde
li t1, 0xdaafe649
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe5cb0348
li t1, 0x653b3758
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2848edfc
li t1, 0xcef0d991
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5f30a999
li t1, 0x5ef2e276
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x94a476fe
li t1, 0x67786cc8
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd79854cc
li t1, 0x97f9713b
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6b1ad683
li t1, 0xf54ceff5
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd67c83ff
li t1, 0xde8e5aeb
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x10c586bd
li t1, 0x3056ae6b
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4e0ee866
li t1, 0x4635cf03
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x252a2ea2
li t1, 0x56db8ea4
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x56b7ddaa
li t1, 0x766805f7
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x13951751
li t1, 0x2b6dc752
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc8dbeed5
li t1, 0xc93402fb
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x20026654
li t1, 0x5b463a38
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7fdd5ef3
li t1, 0x6fe8e30b
divu t2, t0, t1
divu t3, t1, t0
divu t4, t0, t0
divu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

