li t0, 0xd03820c4
li t1, 0xd03820d0
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xd9d7dffb
li t1, 0xf9efff3f
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xad4cdd7b
li t1, 0x5345fe5b
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x18f4b296
li t1, 0x18f46ded
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x8bb7d79a
li t1, 0xebe16fbf
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x95ea6d6d
li t1, 0x151d92d2
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xb8c6a272
li t1, 0xd82f7a69
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x74797d6
li t1, 0x79897d6
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x673a52ce
li t1, 0xdd3e44a6
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xa73dd2
li t1, 0xa7f545
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xb31d2967
li t1, 0x609f2253
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x4eb09ea9
li t1, 0x5e217aa2
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x65179744
li t1, 0x26e468bf
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x477a8e86
li t1, 0x4f1c7183
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x3a8bcba2
li t1, 0x1332345d
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xc6e44743
li t1, 0xc6e438cb
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x87dce626
li t1, 0x9f12e3bc
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xa8fe0220
li t1, 0xaac90220
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xa9773989
li t1, 0x27c4b8ef
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x3ca6634c
li t1, 0xbca6634c
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xf8229f33
li t1, 0x5549a5e5
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x858d6ad0
li t1, 0xc58d6ad0
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xe8884c6e
li t1, 0x340f2b60
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x5577fb0e
li t1, 0x7577fb0e
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x5c442637
li t1, 0x1a0795b0
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x31f6d8a0
li t1, 0x310ad8a0
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x3bb10ec
li t1, 0x1fa8334a
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xc685c71a
li t1, 0xc285c71a
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x835d8876
li t1, 0xdd419a5
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xe1e3ec02
li t1, 0xe3e3c19d
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x7c37c7cc
li t1, 0x9041f540
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x49dcb7d7
li t1, 0x482c2c18
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x8342e011
li t1, 0xdf8b0332
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xfbac9a31
li t1, 0xfad8dada
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xc1017008
li t1, 0xef458199
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x78f6f953
li t1, 0x58dcf953
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xf082b804
li t1, 0x77a2c0cc
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xc1b9368e
li t1, 0xd12626b6
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xf4415c02
li t1, 0x3bd16066
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x82dc9307
li t1, 0x86131b5b
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x78202e01
li t1, 0x1fe8b033
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x5beec9e3
li t1, 0x59818d6d
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x8914f7
li t1, 0x985fa18b
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xa355a543
li t1, 0x234a0a00
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x7cdd898c
li t1, 0x1a842957
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x26881eea
li t1, 0x66231eea
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xa2f7c731
li t1, 0xdbe9ed39
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xbc22c97b
li t1, 0xbc22283d
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xd07be398
li t1, 0xedf4f69c
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x1f7334e2
li t1, 0x1f0d34e2
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xc9903f79
li t1, 0x6abf9925
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x980f1d21
li t1, 0x9c0fcd68
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xf3640fde
li t1, 0x5aafe649
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x9c8b0348
li t1, 0x9d333758
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x793207ef
li t1, 0x2dd7f324
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x61c5a96e
li t1, 0x691da96e
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x6edfc7b3
li t1, 0xfa07493d
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x5c391a77
li t1, 0xa06882d8
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x276fe3d9
li t1, 0xf503a49e
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x351c8d3b
li t1, 0x2534416c
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xb568365f
li t1, 0x50869b72
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0xcb375cea
li t1, 0x8b72a26e
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x946bdc9c
li t1, 0x6a440484
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

li t0, 0x2aa2b402
li t1, 0x2251d3ef
and t2, t0, t1
sw t2, 4(sp)
and t2, t1, t0
sw t2, 4(sp)
and t2, t0, t0
sw t2, 4(sp)
and t2, t1, t1
sw t2, 4(sp)

