li t0, 0xdc991bb7
li t1, 0xdcabfc94
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x3b6ce572
li t1, 0x3a6ccbd3
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x8c8103
li t1, 0x7755fdcb
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x9d554ef4
li t1, 0x9d554ef4
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x270722de
li t1, 0x720103f0
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x48ca9d2e
li t1, 0x4c2c78e5
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xa904aa55
li t1, 0xaf297d6a
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xd2c311ae
li t1, 0xd09e7320
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x1ea02de
li t1, 0xc43d43a5
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x7a94fde0
li t1, 0x7b94b641
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xb95cc747
li t1, 0xbc982651
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x577078a9
li t1, 0x5f2679a6
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x470717c4
li t1, 0xa8e76bbf
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x7c79e57f
li t1, 0x7c79e57f
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x33fbfb22
li t1, 0x3374245d
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xa6089a8e
li t1, 0xa48b9a8e
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x67dcd222
li t1, 0x1912e5bc
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x268e26b5
li t1, 0xa68e52b1
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x52fe7333
li t1, 0x4e8f70d9
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x9d020c3b
li t1, 0x9902ab5f
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xe977bc89
li t1, 0xa1c4baec
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x1bdf66f4
li t1, 0x1f35592b
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xa8209ff3
li t1, 0xc04ca1e7
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x66df4d44
li t1, 0xe630e6c2
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x68e8f062
li t1, 0x640a2a62
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xaf2c4fc8
li t1, 0xef9538b1
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x74c8ee3f
li t1, 0x3e0793b2
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xc9b33582
li t1, 0xe9089eda
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x168330ea
li t1, 0x1bad324b
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xa7fddc9d
li t1, 0xb78a8138
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xd7df0970
li t1, 0xed718a3
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x79eccf1b
li t1, 0x7940c598
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x7d37cfcc
li t1, 0x9840f544
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x28bb2f7
li t1, 0x28b281a
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x8207c011
li t1, 0xdc880330
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x1ce3da3d
li t1, 0x1ee3dada
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xc1117008
li t1, 0xef46819b
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xaee46f5d
li t1, 0xae496f5d
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xe080b824
li t1, 0x57a2c0cc
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x5165368e
li t1, 0x716526b1
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xd2005c02
li t1, 0x3dd16066
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x7d5913c8
li t1, 0x30149b58
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x78602e01
li t1, 0x1de8b033
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x14041701
li t1, 0x14041701
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x188914f7
li t1, 0xc5ea18b
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xb75a503
li t1, 0x1b4bc204
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x2cfd898c
li t1, 0x1a842957
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xde131353
li t1, 0xce13c9d6
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xa0e7c731
li t1, 0x9ae9ed39
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x6672c87c
li t1, 0xc91a283d
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xd17be398
li t1, 0xedf4f69c
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x38e25422
li t1, 0x18e25422
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xd424f23b
li t1, 0xb05182dc
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x353bb3cc
li t1, 0x750ac6d9
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xc9903f79
li t1, 0x6bbf9925
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x2b2c32da
li t1, 0x2ae832da
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xa4cc1fbc
li t1, 0xf55fcc92
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xed486405
li t1, 0xad486405
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xf2640fde
li t1, 0x5aafe649
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x6a8b1748
li t1, 0x6b382358
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x713207ef
li t1, 0x2557f324
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x514583a5
li t1, 0x591899ac
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x3d39fc14
li t1, 0x65c4b276
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x438a6c1f
li t1, 0x435904e0
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x3ebcfe0a
li t1, 0xb263db3b
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xe9a6160f
li t1, 0x69aa80f0
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0xf6278311
li t1, 0x7df5dbeb
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x6e5f2758
li t1, 0x668ac19c
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x664ce2da
li t1, 0x9da5bb7
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

li t0, 0x9f11f356
li t1, 0x3452b170
sra t2, t0, t1
sw t2, 4(sp)
sra t2, t1, t0
sw t2, 4(sp)
sra t2, t0, t0
sw t2, 4(sp)
sra t2, t1, t1
sw t2, 4(sp)

