li t0, 0xdbbfd05
li t1, 0xc3a8f892
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x72c551fe
li t1, 0x7289cb90
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x5b54314b
li t1, 0x7f53ffc9
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xa0adce69
li t1, 0xa0ad616a
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x1303ceea
li t1, 0x620505f6
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe4dcb998
li t1, 0xf42a78e1
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x7166b2f6
li t1, 0x712c7968
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xd6f9698d
li t1, 0xd7187422
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x96bd8a5a
li t1, 0x973a42a3
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x30d271b5
li t1, 0x3840f240
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xff9dc9a7
li t1, 0x64992150
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x3720b478
li t1, 0x3320b478
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xc5f33314
li t1, 0x21e46cb9
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x191ecee6
li t1, 0xbc1a7286
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xb0ebeb4a
li t1, 0x2371305c
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x17dd07b7
li t1, 0x178c3ec2
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xa51cceae
li t1, 0x9f12e4bb
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xd17ce316
li t1, 0xf1cce316
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xc086f3fb
li t1, 0x588a74d8
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xfa5b1115
li t1, 0xea5bae59
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x29df39a9
li t1, 0xa6c5b9e8
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xd767441f
li t1, 0xd772522e
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe8e2c334
li t1, 0x424ba4e2
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xc8d19da
li t1, 0x8c34e3c1
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe8cc4c6e
li t1, 0x320e2b61
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x94584ddc
li t1, 0xd4114ddc
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x74c427f0
li t1, 0x3f0497b5
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x99b6b6db
li t1, 0xb90f98d8
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x46bb90ef
li t1, 0x1caa304d
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x28617a90
li t1, 0x20617a90
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x93d88ef6
li t1, 0xcd51ca4
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xefbbf9e9
li t1, 0xeb40f9e9
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x7c7fc64c
li t1, 0x9141f243
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xb386b2d7
li t1, 0xb22b291c
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x9202e011
li t1, 0xd28b0332
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x9ed49bb7
li t1, 0x9ed4d8dc
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xc1917008
li t1, 0xef428199
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x3d3e184c
li t1, 0x1d44184c
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe480b804
li t1, 0x73a4c0ce
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x237b048a
li t1, 0x272431bc
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xf0405c02
li t1, 0x3bd06066
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x52a469a7
li t1, 0x52a469a7
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x78002e01
li t1, 0x1fe8b033
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x67aec9a3
li t1, 0x998b8ba9
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xa914f7
li t1, 0x1d5fa389
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xbd55e50b
li t1, 0xd84b0c03
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x3cdd898c
li t1, 0x1a842957
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xc42a1353
li t1, 0xc52ac9d6
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xa0f7c731
li t1, 0x9bebed39
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x464ee879
li t1, 0xe81a293e
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x517be398
li t1, 0x4df4f69c
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x9431d7bb
li t1, 0x140ad7bb
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xd524f23b
li t1, 0xf05182dc
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x743b73cd
li t1, 0x758806d8
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe212791d
li t1, 0xf028c16e
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xbe7838ae
li t1, 0xb67838ae
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xc9903f79
li t1, 0x68bf9925
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x5c291d20
li t1, 0x5ee8cf60
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe6c89fbc
li t1, 0xb55fcc92
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x18e76c4d
li t1, 0x1ae76c4d
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xf2600fde
li t1, 0xdaaee649
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x248b2340
li t1, 0xa439335c
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x793227ef
li t1, 0x2d57f324
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xf73083e4
li t1, 0xff309bac
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xe09c501b
li t1, 0x4bf8ad34
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x1b58ca2c
li t1, 0x5b4e4801
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xea4e288d
li t1, 0x81fc541b
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x81846716
li t1, 0x91202705
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xcbb441d
li t1, 0xcb068239
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x3f0afda7
li t1, 0x3dda5d81
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x36c1f215
li t1, 0xef7be928
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xce0db0ff
li t1, 0x8e2560c1
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x4bfca911
li t1, 0xfc455ca0
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xdb8e1653
li t1, 0xdb5afe61
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xa5fe5488
li t1, 0xfe22ae50
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0xbd470b29
li t1, 0x3dad7f30
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x2a637a5f
li t1, 0x74e9ff1c
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x752b4bb8
li t1, 0xd29ef199
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x9131bd2f
li t1, 0xba74ff8e
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

li t0, 0x3d95a5dc
li t1, 0x69cf78cc
srl t2, t0, t1
sw t2, 4(sp)
srl t2, t1, t0
sw t2, 4(sp)
srl t2, t0, t0
sw t2, 4(sp)
srl t2, t1, t1
sw t2, 4(sp)

