li t0, 0x301111c1
li t1, 0x536743c2
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xcdd16111
li t1, 0xcdd16e28
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x57ea513b
li t1, 0xbc50c25
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x7719a279
li t1, 0x11a3187
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xa0094e7f
li t1, 0xaa0a04d7
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xbcbb0c3
li t1, 0x58240903
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x69df64e7
li t1, 0x520b319c
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x9130490a
li t1, 0x3775906b
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x71a4504
li t1, 0x275e3065
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x98988205
li t1, 0x99578205
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x7ca9c011
li t1, 0x43443074
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xc326235b
li t1, 0x162e35c5
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x83ae1470
li t1, 0x83004b01
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x84f34a2c
li t1, 0x39c93e5b
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x8ac102c7
li t1, 0x902747f5
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x6d3f8be9
li t1, 0x6d92903a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x9e188672
li t1, 0x8836a72f
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x7edc620b
li t1, 0x3ee95827
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x4a0133b
li t1, 0x27af5c86
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x9d6c8ad
li t1, 0x13d50de
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xf9f0f3d
li t1, 0x40519083
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x94a109c4
li t1, 0xfbe64864
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x9912a111
li t1, 0x311dd17f
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x160925e4
li t1, 0xce7f8c50
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x8060026e
li t1, 0x1a5555b0
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x7eec8c28
li t1, 0x1906037f
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x75303d6a
li t1, 0x4e6f945a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xbb218b05
li t1, 0x847f7615
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x44a33ae8
li t1, 0x99a2715f
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xf8a04db6
li t1, 0xf8830fc2
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x135d9936
li t1, 0xdde5041
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xa6dc04c7
li t1, 0x471c513c
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x7d37c7cc
li t1, 0xd801e960
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xb5043531
li t1, 0xb5487619
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x9006201d
li t1, 0xcc4f336a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x1a2a3527
li t1, 0x9a924fca
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x8c6d600c
li t1, 0xb1419181
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xc773509c
li t1, 0xc7736be9
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x66800000
li t1, 0x612203ac
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x3b3bfd62
li t1, 0x7b8e1e12
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xd0015c00
li t1, 0x3a716066
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xbfddd70e
li t1, 0xbff762db
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x62203005
li t1, 0x37683433
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x4d364f5b
li t1, 0x6dc9051d
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x689c14f5
li t1, 0x10e18a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xf91ba725
li t1, 0xf9cf2109
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x3c1dc98c
li t1, 0x1a242b57
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x4940064f
li t1, 0x4927a5cf
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xe0f0c776
li t1, 0x9beded11
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xaa75cb3f
li t1, 0xaa030012
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x6a7be39a
li t1, 0x6af5f69d
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x15306434
li t1, 0x170b941b
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xd424f23b
li t1, 0xf05180dc
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x54b4700
li t1, 0x798107d
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xea12791d
li t1, 0xf928c16e
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xff3b9bf6
li t1, 0xfec0016c
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xc9b03f78
li t1, 0x2abf9925
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x2d0a0d21
li t1, 0x25c0dc60
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xe4c81fbc
li t1, 0xb55fcc92
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x6d16de90
li t1, 0x8466e2b0
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xf2640fde
li t1, 0x5aafe649
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x368b0e48
li t1, 0x4133305c
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x713a07ef
li t1, 0x2557f324
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x37907c3a
li t1, 0x3f907c3a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x549c0725
li t1, 0x81e9a80f
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xae2e1b7c
li t1, 0xbe7841bd
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xe04e07c8
li t1, 0x44f45497
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x3a062870
li t1, 0xba9f6527
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x809b06f9
li t1, 0xa0a2820c
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xade07a55
li t1, 0xac8d20e1
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x90418448
li t1, 0x5121a909
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x584d37cd
li t1, 0x5c104060
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xbebcc510
li t1, 0xf9785c8b
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xf76391d
li t1, 0x1f825f86
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x8f466288
li t1, 0x74bc0e45
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xd0bb4c8e
li t1, 0xa1412395
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x93333670
li t1, 0xabb6bf2d
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x46156850
li t1, 0x469a0318
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x49989b39
li t1, 0xd5db5d96
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xcf0bc649
li t1, 0x4f5c57fd
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x3050caa9
li t1, 0xaf0507c4
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xb4cc41fa
li t1, 0xb01c81c0
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x98286554
li t1, 0x548283e2
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xa466a0ff
li t1, 0xa50e40e2
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x4c1432aa
li t1, 0x2ac141f1
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x1b1b507f
li t1, 0x19c7a071
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xf2961e61
li t1, 0x948808f7
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xb89100e4
li t1, 0x3f9ba02
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xafd70804
li t1, 0x8acac74
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x97c0e5a9
li t1, 0xd746f63b
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x56eb8402
li t1, 0x65d6563a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x64e073d4
li t1, 0x24237b9d
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xefe9c535
li t1, 0x93038312
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x18781b31
li t1, 0x82b97f4
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x7ff4e29a
li t1, 0xc981c189
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x84bc0d98
li t1, 0xa495cbfa
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xcb667679
li t1, 0xe52848cb
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x6c562417
li t1, 0x4cf0cfc7
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x292f3c08
li t1, 0x737c8c6a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xb22330d0
li t1, 0xbac24dd9
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x14979e04
li t1, 0x3dbe4635
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xd3919868
li t1, 0xd76126ec
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0x884bcf02
li t1, 0x1cdf231a
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

li t0, 0xe1c8cc34
li t1, 0xe1309376
sub t2, t0, t1
sw t2, 4(sp)
sub t2, t1, t0
sw t2, 4(sp)
sub t2, t0, t0
sw t2, 4(sp)
sub t2, t1, t1
sw t2, 4(sp)

