li t0, 0x49903f7
li t1, 0xe7abf992
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb50285f5
li t1, 0xa50285f5
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfe4c81fb
li t1, 0xb55fcc9
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1fd160e9
li t1, 0x2147666b
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd3bf430a
li t1, 0x330107f6
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9c4a71a6
li t1, 0xc62d7fe3
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb546a272
li t1, 0xaf2b7a69
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6987f901
li t1, 0xd9987327
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x63a52ce
li t1, 0xe93e44a6
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf54dfcee
li t1, 0xd54dfcee
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x57179744
li t1, 0x57e468bb
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6c93b2b6
li t1, 0x5c93b2b6
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x328bcba2
li t1, 0x1372345d
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xccbd4743
li t1, 0xde8f38c3
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa5dce626
li t1, 0x9f12e3bc
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1efc6273
li t1, 0xec950b7
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x52ee7313
li t1, 0x4f8971de
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5fe3139
li t1, 0x5e4a85b
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x23773989
li t1, 0xa7c4b8ef
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea34189d
li t1, 0xe234542c
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa8229f33
li t1, 0x4549a5e5
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x709d4d9c
li t1, 0x7037e6c0
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe0884c6e
li t1, 0x340f2b60
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2c6e2c98
li t1, 0x28152c98
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x74442637
li t1, 0x1a0795b0
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x68b6338e
li t1, 0x680a9fdb
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbb10ec
li t1, 0x1ba8334a
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfeb7d815
li t1, 0xfcb7833a
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x835d8876
li t1, 0xdd419a5
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3c7cec0a
li t1, 0x3c45c19d
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7c37c7cc
li t1, 0xb541f540
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdb9cb7d7
li t1, 0xda2c2c18
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe080b804
li t1, 0xf7a2c0cc
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa2fb268e
li t1, 0x222676b6
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x78202e01
li t1, 0x1de8b033
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2feec9a3
li t1, 0x3b898dad
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd17be398
li t1, 0xc5f4f69c
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb933643d
li t1, 0xb90d941e
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdc24f23b
li t1, 0xf85182dc
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1a3b73cc
li t1, 0x128004d9
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea12791d
li t1, 0xf828c16e
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfe1db9e6
li t1, 0xfec4036c
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcd903f79
li t1, 0x6ebf9925
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcdbd8b86
li t1, 0xc9bd8b86
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf2640fde
li t1, 0x5aafe649
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x978b0748
li t1, 0x95393378
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x793207ef
li t1, 0x2c57f324
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6b4583a4
li t1, 0x6b1d99ac
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc291f3c0
li t1, 0xbe25b877
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa184d2a6
li t1, 0xa0cbb7e0
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x61c8f9e0
li t1, 0x5f12dc3b
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x11426953
li t1, 0x1065dbf0
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf3758f30
li t1, 0xb32cd66a
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa6a5e60f
li t1, 0x86795a18
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3a2b3458
li t1, 0xb5b3d342
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe35621a1
li t1, 0xa3771aec
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5e8469ec
li t1, 0xc2fc51d6
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa2fc276
li t1, 0xcf03a96
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2f4234f6
li t1, 0x607e28eb
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2a17e13b
li t1, 0x2b781d4b
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdc30e9bb
li t1, 0x859aac02
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc70f223b
li t1, 0xc877b945
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea1874dd
li t1, 0xc6cd5601
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x87911d
li t1, 0x1bbdca2
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x369dc9ae
li t1, 0x4f431377
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe9c71a28
li t1, 0xf49659b1
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1b4ee4d7
li t1, 0x6fa189bb
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf9e38d14
li t1, 0xb94b2cd8
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xda7726b
li t1, 0x17d0c4dd
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7271c68a
li t1, 0xad25966c
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x45424af5
li t1, 0x77cdda19
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9fbc31e3
li t1, 0x1f597cd6
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2130d6ba
li t1, 0x7c3557b
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x765aca57
li t1, 0x7ae7098b
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x10986b5d
li t1, 0x3e1aabd
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2e2d652b
li t1, 0x2f7384c5
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4bddc66e
li t1, 0x3dd56d29
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x19126033
li t1, 0x1a727582
p.sletu t2, t0, t1
p.sletu t3, t1, t0
p.sletu t4, t0, t0
p.sletu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

