li t0, 0xb09903f7
li t1, 0xb4abf992
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa802c1d2
li t1, 0x8802ccd6
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9e4c81fb
li t1, 0x4b55fcc9
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd9d342a0
li t1, 0x994542a0
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7fbf430a
li t1, 0x810107f6
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1c4a71a6
li t1, 0x262d7fe3
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7546a272
li t1, 0x2f2b7a69
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa987f901
li t1, 0xd9987327
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb31d2967
li t1, 0x609f2253
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2db09ea9
li t1, 0xdf217aa2
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x36179744
li t1, 0x36e468bb
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf97a8e86
li t1, 0xdd1e7187
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x85dce626
li t1, 0x9f12e3bc
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf1fc6273
li t1, 0xddc950b7
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x72ee7313
li t1, 0xcf8971de
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8dfe3139
li t1, 0x8de4a85b
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x69773989
li t1, 0xe7c4b8ef
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdb7b0ab7
li t1, 0xcb760ab7
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb8229f33
li t1, 0x4549a5e5
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6c9d4d9c
li t1, 0x6c37e6c0
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc0884c6e
li t1, 0x3c0f2b60
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6d182df1
li t1, 0x65182df1
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7c442637
li t1, 0x1a0795b0
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x46b6338e
li t1, 0x460a9fdb
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2bb10ec
li t1, 0x1fa8334a
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x74cc32c4
li t1, 0x70cc32c4
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x875d8876
li t1, 0xdd419a5
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa37cec0a
li t1, 0xa345c19d
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7d37c7cc
li t1, 0x9041f540
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe3b7b7d7
li t1, 0xe1b72c18
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc0017008
li t1, 0xee458199
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcb780dec
li t1, 0xca780dec
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe180b804
li t1, 0x77a2c0cc
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x62bb268e
li t1, 0x622636b6
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3cdd898c
li t1, 0x5a842957
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb3881353
li t1, 0x9d2bc9d6
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa2f7c731
li t1, 0x9be9ed39
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe466c87b
li t1, 0xfd1b283d
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd17be398
li t1, 0xcdf4f69c
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb533643d
li t1, 0xb50d941e
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc424f23b
li t1, 0xf05182dc
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xff3b73cc
li t1, 0xef8806d9
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea12791d
li t1, 0xf028c16e
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbf1db9e6
li t1, 0xbfc4036c
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe4c81fbc
li t1, 0xb55fcc92
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5756d2b3
li t1, 0x5336d2b3
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x793207ef
li t1, 0x2f57f324
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3f33b980
li t1, 0x3d33b980
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa91d24f6
li t1, 0xcbfdf472
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1ba20b61
li t1, 0x1a3e2c41
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd40e927b
li t1, 0x65fefa39
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xaad105b0
li t1, 0xa29f1620
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x421a6dcb
li t1, 0x7902896e
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1fca89b9
li t1, 0x9ff1a751
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x89101213
li t1, 0x377cb0c5
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5e474fbd
li t1, 0x1e46ffe9
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6c952dff
li t1, 0x7843ac10
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf01acbf
li t1, 0x71d53b5
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbe4a96ff
li t1, 0x3021d608
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe380d65f
li t1, 0xe48ea9da
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xff386f89
li t1, 0x5ed1f76
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3262604e
li t1, 0x337978ac
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x399c37c4
li t1, 0x83f68fbb
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4b13027
li t1, 0xabcbc56
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x34d33f14
li t1, 0x8e06b3af
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6ffa9372
li t1, 0x7260726a
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9a699f8a
li t1, 0x470359d7
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9dfd49b9
li t1, 0x9c303935
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcd34cfc5
li t1, 0x2381aceb
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xaffea4dc
li t1, 0x8f981c9a
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xce874314
li t1, 0xda3d2207
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea5d590f
li t1, 0x6f72220c
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcf5e857c
li t1, 0xe6e36571
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x368ca7e6
li t1, 0xb6873d47
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x27af42be
li t1, 0x7371b2b8
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd3c653f3
li t1, 0x4439ea3
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbbca85a9
li t1, 0xf2452d2e
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x64412298
li t1, 0x671fe310
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdfe542d4
li t1, 0x71229697
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9d20914c
li t1, 0x9e8ff188
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc6ef859c
li t1, 0xb76cbf39
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa43243c7
li t1, 0xa5f9d485
p.slet t2, t0, t1
p.slet t3, t1, t0
p.slet t4, t0, t0
p.slet t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

