li t0, 0x869903f7
li t1, 0x86abf992
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5ce281d2
li t1, 0xdc8eccd6
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbb4c81fb
li t1, 0xc155fcc9
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x54d1af2d
li t1, 0x5407af2d
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3bf430a
li t1, 0x230107f6
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x294b71a6
li t1, 0x692c7fe3
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8146a272
li t1, 0xd2b7a69
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7287f101
li t1, 0x72987b27
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x673a52ce
li t1, 0xc13e44a6
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfa613d52
li t1, 0xfb02f54d
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x991d2967
li t1, 0x489f2253
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa97c9ee9
li t1, 0xab7c7aa2
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x34179744
li t1, 0x56e468bb
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x697a8e86
li t1, 0x691f718f
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x328bcba2
li t1, 0x1172345d
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8884743
li t1, 0xa8838c3
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa5dce626
li t1, 0x8f12e3bc
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1afe6273
li t1, 0xac950bf
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x12ee7313
li t1, 0x4f8971de
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd7af6307
li t1, 0x97af6307
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf8229f33
li t1, 0x4649a5e5
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb19d41c8
li t1, 0xb12741c8
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf8884c6e
li t1, 0x240f2b60
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x46c3a05
li t1, 0x14153a05
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x74442637
li t1, 0x1a0795b0
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x56b2328e
li t1, 0x540e9fdb
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x26bb10ec
li t1, 0x1ba8334a
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xff9d815
li t1, 0x2f8b833b
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x835d8876
li t1, 0x5d419a5
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc45aac0a
li t1, 0xcc5ac19d
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7437c7cc
li t1, 0xb041f540
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdd584a95
li t1, 0xdd584a95
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8202e011
li t1, 0x5e8b0332
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6dec9a39
li t1, 0xed98dada
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc1017008
li t1, 0xef458199
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2e584d1c
li t1, 0x2a586f6d
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf0405c02
li t1, 0x3bd16066
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1d709147
li t1, 0x5d701b5b
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd17be398
li t1, 0xcdf4f69c
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc343643d
li t1, 0xe343941e
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea12791d
li t1, 0xf028c16e
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7243b9e6
li t1, 0x7a43036c
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc8903f79
li t1, 0x6abf9925
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x22c1d21
li t1, 0x3edcc60
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe0c81fbc
li t1, 0xb15fcc92
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8c1e5906
li t1, 0x88765906
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfa640fde
li t1, 0x5aafe649
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x88e3495f
li t1, 0x80e3495f
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7d3207ef
li t1, 0x2957f324
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x39559039
li t1, 0x3d0d9039
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4bb2850a
li t1, 0xa2353557
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x621167be
li t1, 0x4272a48a
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x34d94285
li t1, 0x511a9aab
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd988b3df
li t1, 0xd8395245
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x715e2448
li t1, 0x1ab87802
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf8553e51
li t1, 0xe86e0da8
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x531d972e
li t1, 0xa7690956
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2abbf896
li t1, 0x22c5a25e
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x423c4e9d
li t1, 0xf181b1fc
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdecc9bf5
li t1, 0x5e9075a5
remu t2, t0, t1
remu t3, t1, t0
remu t4, t0, t0
remu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

