li t0, 0x3dd93fbf
li t1, 0xb7fb3ebb
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdcaf0040
li t1, 0x5cafc104
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb4ef0160
li t1, 0x5aa7f904
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd08f813
li t1, 0xd5006e8
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x49bf4002
li t1, 0x790107e4
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x96ba47ac
li t1, 0x96ba7813
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x150ea272
li t1, 0x8e2b7a69
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe7c7628b
li t1, 0xe790628b
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb43a52ce
li t1, 0xb43e44a6
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd308b452
li t1, 0xba08b452
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd11d2867
li t1, 0xd19f2253
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x85489ea9
li t1, 0x95487ba2
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x65179744
li t1, 0x26e468fb
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x39e8686
li t1, 0x439e7987
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x35dce626
li t1, 0x3512e3bc
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x98fcf4b0
li t1, 0x9c89f4b0
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5bee7313
li t1, 0x4f8971de
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf0fe6d3a
li t1, 0xf0e46d3a
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x29773989
li t1, 0xa6c4b8ef
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x737f18dc
li t1, 0x7370542d
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe8229f33
li t1, 0x4549a5e5
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2271aa7f
li t1, 0x6271aa7f
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe8884c6e
li t1, 0x140f2b60
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xce6c661c
li t1, 0xee953fb6
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x64442637
li t1, 0x1a0795b0
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x75b6338e
li t1, 0x750a9fdb
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4bb10ec
li t1, 0x11a8334a
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x18f9e5ee
li t1, 0x108be5ee
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x835d8876
li t1, 0xdd419a5
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdc7c752b
li t1, 0xd845752b
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7d37c7cc
li t1, 0x9041f540
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x439cb7d7
li t1, 0x432c2c18
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8202e011
li t1, 0xde8b0332
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3434f488
li t1, 0x3634f488
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc1017008
li t1, 0xef458199
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc272dff1
li t1, 0xc24cdff1
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc000b804
li t1, 0x57a2c0cc
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7ebb260e
li t1, 0x5e263676
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf0405c02
li t1, 0x3bd16066
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1edbf00
li t1, 0x500bf00
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x78202e01
li t1, 0x1ce8b033
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf3fec9a3
li t1, 0xf2898dac
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8114f7
li t1, 0x185fa18b
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe95da503
li t1, 0xeb420a00
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xaaf5c731
li t1, 0x9be9ed39
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb166c87b
li t1, 0xb919283c
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x917ae398
li t1, 0xcdf4f69c
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd233643d
li t1, 0x920c951e
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd524f23b
li t1, 0xf15182dc
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x657b71cc
li t1, 0x648806d9
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe812791d
li t1, 0xfa28c16e
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xff40a744
li t1, 0xfd40a744
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc9903f79
li t1, 0x62bf9925
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xed2a1c01
li t1, 0xed2acc60
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe4c81ffc
li t1, 0x355fcc92
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb14a611
li t1, 0x8b76a611
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf2640fde
li t1, 0x4aafe649
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x619bc322
li t1, 0x712bc322
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1cf3fdd5
li t1, 0x14873ebc
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb0b64413
li t1, 0x30aa5e0f
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8f79feea
li t1, 0xca439f5e
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe0db2209
li t1, 0xe1552f07
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4bcf02a0
li t1, 0xf1a6f113
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x325bd517
li t1, 0x2280c98c
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x31147c85
li t1, 0xec544635
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x209bae98
li t1, 0xea3ac9
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8479c397
li t1, 0x62ad1da6
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x91fb935f
li t1, 0x995f436b
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc23ce1cb
li t1, 0xb9568ed3
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc8fdc9af
li t1, 0xc02fa1b5
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfded8d30
li t1, 0xcc2c79d5
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa248a0c4
li t1, 0x223d8ed5
or t2, t0, t1
or t3, t1, t0
or t4, t0, t0
or t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

