li t0, 0x209903f7
li t1, 0xe1abf992
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdea07769
li t1, 0xde8e7769
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe74c81fb
li t1, 0x5e55fcc9
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x99013dfd
li t1, 0x99013dfd
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1fbf430a
li t1, 0x1f0107f6
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x925a70a6
li t1, 0xb22d7fe3
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb546a272
li t1, 0xaf2b7a69
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd18fb901
li t1, 0xd0907327
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfa3a52ce
li t1, 0x953e44a6
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4598e1d7
li t1, 0x4598e180
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe31d2967
li t1, 0x609f2253
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbf309ea9
li t1, 0xffa17ba2
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x61179744
li t1, 0x26e468bb
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa77a8f86
li t1, 0xa31f7087
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x228bcba2
li t1, 0x372345d
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbbc77d9
li t1, 0x1b8f77d9
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa5dce626
li t1, 0x9f12e3bc
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x23fe6273
li t1, 0x63c950bf
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x52ee7313
li t1, 0x4e8971de
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe54cd3f4
li t1, 0xe44cd3f4
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x29773989
li t1, 0xe7c4b8ef
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xee1f199c
li t1, 0xae1f542d
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa8229f33
li t1, 0x5549a5e5
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x99dd459c
li t1, 0x8937eec0
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe8884c6e
li t1, 0x360f2b60
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4b7e671c
li t1, 0x497e3eb6
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x74442637
li t1, 0x1a0795b0
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc7b6338e
li t1, 0xe70a9fdb
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6bb10ec
li t1, 0x5aa8334a
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe555f30c
li t1, 0xe555f30c
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8b5d8876
li t1, 0x5d419a5
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x427c14cc
li t1, 0x4a4514cc
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xfd37c7cc
li t1, 0x9041f540
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcb9cb5d7
li t1, 0x4b2c2e18
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8602e011
li t1, 0xda8b0332
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd9ec9a39
li t1, 0xdd98dada
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf2405c02
li t1, 0x3bd16066
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x31dd4bfc
li t1, 0x33134bfc
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x79202e01
li t1, 0x15e8b033
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4cea4caa
li t1, 0x4c8d4caa
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x34dd898c
li t1, 0x12842957
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x78de1353
li t1, 0x70dec9de
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa2f7c731
li t1, 0x9be9ed39
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcd13e77a
li t1, 0xc913e77a
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd97be398
li t1, 0xcdf4f69c
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x457d643d
li t1, 0x4d7d945e
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd424f23b
li t1, 0xf05182dc
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x254e73cc
li t1, 0x274e0ed9
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc4c81fbc
li t1, 0xb55fcc92
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf5565f03
li t1, 0xd5365f03
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf3640fde
li t1, 0x5aafe649
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x80898425
li t1, 0x813b8425
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9fe0bdb8
li t1, 0xacc1b6fe
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4e0f9d2a
li t1, 0x5e997694
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc7f05edc
li t1, 0x5e60db7f
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2e07ce95
li t1, 0x26ccbb4a
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xec1892d6
li t1, 0x7f1db41
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x688c7a60
li t1, 0xe8ff2b31
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x39ecf4d3
li t1, 0xef395b5e
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa0c9a01a
li t1, 0x20e6e30c
div t2, t0, t1
div t3, t1, t0
div t4, t0, t0
div t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

