li t0, 0x6c9903f7
li t1, 0x68abf992
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2ea2c1d2
li t1, 0x968eccd6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x1e4c81fb
li t1, 0xcb55fcc9
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x87d160e9
li t1, 0x947666b
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x93bf430a
li t1, 0x930107f6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xec4a9440
li t1, 0xf62d9440
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3c46a272
li t1, 0xf52b7a69
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8b755266
li t1, 0x8b755266
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3a52ce
li t1, 0xfb3e44a6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf7613d52
li t1, 0xf542f545
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5f179744
li t1, 0x24e468bb
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb2d78e86
li t1, 0xb2d771c7
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb28bcba2
li t1, 0x1372345d
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3abd4743
li t1, 0xba8f38c3
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd2ee7313
li t1, 0xf8971de
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x28fe3139
li t1, 0x5ee4a85b
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9773989
li t1, 0xa7c4b8ef
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x247f189c
li t1, 0xf72542d
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa8229f33
li t1, 0x4549a5e5
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x59d4d9c
li t1, 0x1537e6c0
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe7884c6e
li t1, 0x320f2b60
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x586c671c
li t1, 0x58173db6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x74442637
li t1, 0x5a0795b0
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6db6338e
li t1, 0x7d0a9fdb
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6bb10ec
li t1, 0x1aa8334a
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbf2e9815
li t1, 0xbf2ec33b
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x835d8876
li t1, 0xcd419a5
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x477c7572
li t1, 0x47c57572
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xff37c7cc
li t1, 0x241f540
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9cb7d7
li t1, 0x22c2c18
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc1017008
li t1, 0xee458199
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf4364d1c
li t1, 0xf54c6d6d
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf0405c02
li t1, 0xbbd16066
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4e65b16
li t1, 0x4e65b16
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x8914f7
li t1, 0x585fa18b
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3c55a503
li t1, 0x34a0a00
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd424f23b
li t1, 0xf05182dc
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x323b73cc
li t1, 0x368806d9
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc8903f79
li t1, 0x6abf9925
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x542c1d21
li t1, 0x55eccd60
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xda640fde
li t1, 0x5aafe649
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x408b0748
li t1, 0x483b3358
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x793207ef
li t1, 0x2957f324
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xda0583a4
li t1, 0xde5d99ac
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x4248b883
li t1, 0x54ed709a
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x149f6f8c
li t1, 0x1ce2ac07
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa1245c41
li t1, 0xaa76b84d
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7a4fb7c6
li t1, 0xfaf15603
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x92da96a3
li t1, 0x81d62cbc
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf4b8b46f
li t1, 0xf69a0706
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb25f3d2
li t1, 0x950666c4
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x904335bb
li t1, 0x91afaf84
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc7da416a
li t1, 0x1eee43f8
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x86bef551
li t1, 0xa6357bc5
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x23ed20b5
li t1, 0xf7721fc
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x39df7aa8
li t1, 0x799abde2
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x72be28d9
li t1, 0xd756e064
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe970d2d8
li t1, 0xe8aff2f6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x39df146c
li t1, 0xe1ab7032
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x3538696c
li t1, 0x38d7f97b
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x56a732b5
li t1, 0x2038c883
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xf8835b3a
li t1, 0xf60950ba
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xaf53995a
li t1, 0xb01c6441
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x5141ad9d
li t1, 0x4c04a85d
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd7a9ccad
li t1, 0x480e3220
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x14a0d6ce
li t1, 0x5402542e
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa99c5ed5
li t1, 0xf0ea698a
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x84cf04eb
li t1, 0xa4e38610
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xcb434bf4
li t1, 0xc64c222f
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xea7c76fc
li t1, 0xf3c9b787
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xa7e91d79
li t1, 0x1fcb618d
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x19a154f2
li t1, 0x240677c4
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x53f48ebc
li t1, 0x9fe5b0c6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x9cd0aa79
li t1, 0x9a033be2
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x6bb2ffdd
li t1, 0x111fa8f9
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2df73ab0
li t1, 0x2ee331f6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x7591c76d
li t1, 0xd962a4e6
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x27e4f2d4
li t1, 0x269334fc
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xbfc8e3b6
li t1, 0xe8b15273
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xe2f2796a
li t1, 0xe5c99a7e
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xdde471db
li t1, 0x7458a939
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x32793cb5
li t1, 0x33e4cd3f
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0x2ef238ed
li t1, 0xfb2c549c
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xd13c9e5a
li t1, 0xb672669f
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xb7791c76
li t1, 0xdd962a4e
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

li t0, 0xc89e4f2d
li t1, 0xc339334f
sltu t2, t0, t1
sltu t3, t1, t0
sltu t4, t0, t0
sltu t5, t1, t1
sw t2, 4(sp)
sw t3, 8(sp)
sw t4, 12(sp)
sw t5, 16(sp)

